version: '3'

services:
  # Database container for PostgreSQL
  db:
    image: postgres:12
    volumes:
      - db_volume:/var/lib/postgresql/data:delegated
    env_file:
      - config/db/db_env

  # Backend container, with both Django + Gunicorn
  backend:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE
    volumes:
      - .:/opt/services/backend/src:delegated
      - static:/opt/services/backend/static:delegated
      - media:/opt/services/backend/media:delegated
    depends_on:
      - db

  #  Frontend container for ReactJS
  frontend:
    image: node:14.9-buster
    working_dir: /frontend
    stdin_open: true
    command: ["bash", "-c", "npm install && npm start"]
    volumes:
      - ./frontend:/frontend:delegated
    ports:
      - 127.0.0.1:3000:3000
    depends_on:
      - backend

  # Reverse proxy container for Nginx
  nginx:
    image: nginx:1.19
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/backend/static
      - media:/opt/services/backend/media
    depends_on:
      - backend

  # Container specifically for Celery workers
  worker:
    working_dir: /opt/services/backend/src/backend
    build: .
    depends_on:
      - redis
    command: sh -c "celery worker -A backend --loglevel=INFO && celery -A backend --beat"
    volumes:
      - .:/opt/services/backend/src:delegated
      - static:/opt/services/backend/static:delegated
      - media:/opt/services/backend/media:delegated

  #  Message queue for handling Celery tasks
  redis:
    image: redis:6.0.6

# Persist certain volumes
volumes:
  db_volume:
  static:
  media:
  node-modules:

